// Auto-generated by scripts/generate-manifest.mjs — do not edit manually
import type { StageCategories } from '../types'

export const assetManifest: StageCategories = {
  "background": [
    {
      "id": "logo_bg_1",
      "name": "Bg 1",
      "path": "/assets/backgrounds/logo_bg_1",
      "assets": [
        {
          "id": "logo_bg_1_30001",
          "filename": "30001.png",
          "path": "/assets/backgrounds/logo_bg_1/30001.png"
        },
        {
          "id": "logo_bg_1_30002",
          "filename": "30002.png",
          "path": "/assets/backgrounds/logo_bg_1/30002.png"
        },
        {
          "id": "logo_bg_1_30003",
          "filename": "30003.png",
          "path": "/assets/backgrounds/logo_bg_1/30003.png"
        },
        {
          "id": "logo_bg_1_30004",
          "filename": "30004.png",
          "path": "/assets/backgrounds/logo_bg_1/30004.png"
        },
        {
          "id": "logo_bg_1_30005",
          "filename": "30005.png",
          "path": "/assets/backgrounds/logo_bg_1/30005.png"
        },
        {
          "id": "logo_bg_1_30006",
          "filename": "30006.png",
          "path": "/assets/backgrounds/logo_bg_1/30006.png"
        },
        {
          "id": "logo_bg_1_30007",
          "filename": "30007.png",
          "path": "/assets/backgrounds/logo_bg_1/30007.png"
        },
        {
          "id": "logo_bg_1_30008",
          "filename": "30008.png",
          "path": "/assets/backgrounds/logo_bg_1/30008.png"
        },
        {
          "id": "logo_bg_1_30009",
          "filename": "30009.png",
          "path": "/assets/backgrounds/logo_bg_1/30009.png"
        },
        {
          "id": "logo_bg_1_30010",
          "filename": "30010.png",
          "path": "/assets/backgrounds/logo_bg_1/30010.png"
        },
        {
          "id": "logo_bg_1_30011",
          "filename": "30011.png",
          "path": "/assets/backgrounds/logo_bg_1/30011.png"
        },
        {
          "id": "logo_bg_1_30012",
          "filename": "30012.png",
          "path": "/assets/backgrounds/logo_bg_1/30012.png"
        },
        {
          "id": "logo_bg_1_30013",
          "filename": "30013.png",
          "path": "/assets/backgrounds/logo_bg_1/30013.png"
        },
        {
          "id": "logo_bg_1_30014",
          "filename": "30014.png",
          "path": "/assets/backgrounds/logo_bg_1/30014.png"
        },
        {
          "id": "logo_bg_1_30015",
          "filename": "30015.png",
          "path": "/assets/backgrounds/logo_bg_1/30015.png"
        },
        {
          "id": "logo_bg_1_30016",
          "filename": "30016.png",
          "path": "/assets/backgrounds/logo_bg_1/30016.png"
        },
        {
          "id": "logo_bg_1_30017",
          "filename": "30017.png",
          "path": "/assets/backgrounds/logo_bg_1/30017.png"
        },
        {
          "id": "logo_bg_1_30018",
          "filename": "30018.png",
          "path": "/assets/backgrounds/logo_bg_1/30018.png"
        },
        {
          "id": "logo_bg_1_30019",
          "filename": "30019.png",
          "path": "/assets/backgrounds/logo_bg_1/30019.png"
        },
        {
          "id": "logo_bg_1_30020",
          "filename": "30020.png",
          "path": "/assets/backgrounds/logo_bg_1/30020.png"
        },
        {
          "id": "logo_bg_1_30021",
          "filename": "30021.png",
          "path": "/assets/backgrounds/logo_bg_1/30021.png"
        },
        {
          "id": "logo_bg_1_30022",
          "filename": "30022.png",
          "path": "/assets/backgrounds/logo_bg_1/30022.png"
        },
        {
          "id": "logo_bg_1_30023",
          "filename": "30023.png",
          "path": "/assets/backgrounds/logo_bg_1/30023.png"
        },
        {
          "id": "logo_bg_1_30024",
          "filename": "30024.png",
          "path": "/assets/backgrounds/logo_bg_1/30024.png"
        },
        {
          "id": "logo_bg_1_30025",
          "filename": "30025.png",
          "path": "/assets/backgrounds/logo_bg_1/30025.png"
        },
        {
          "id": "logo_bg_1_30026",
          "filename": "30026.png",
          "path": "/assets/backgrounds/logo_bg_1/30026.png"
        },
        {
          "id": "logo_bg_1_30027",
          "filename": "30027.png",
          "path": "/assets/backgrounds/logo_bg_1/30027.png"
        },
        {
          "id": "logo_bg_1_30028",
          "filename": "30028.png",
          "path": "/assets/backgrounds/logo_bg_1/30028.png"
        },
        {
          "id": "logo_bg_1_30029",
          "filename": "30029.png",
          "path": "/assets/backgrounds/logo_bg_1/30029.png"
        },
        {
          "id": "logo_bg_1_30030",
          "filename": "30030.png",
          "path": "/assets/backgrounds/logo_bg_1/30030.png"
        },
        {
          "id": "logo_bg_1_30031",
          "filename": "30031.png",
          "path": "/assets/backgrounds/logo_bg_1/30031.png"
        },
        {
          "id": "logo_bg_1_30032",
          "filename": "30032.png",
          "path": "/assets/backgrounds/logo_bg_1/30032.png"
        },
        {
          "id": "logo_bg_1_30033",
          "filename": "30033.png",
          "path": "/assets/backgrounds/logo_bg_1/30033.png"
        }
      ]
    },
    {
      "id": "logo_bg_2",
      "name": "Bg 2",
      "path": "/assets/backgrounds/logo_bg_2",
      "assets": [
        {
          "id": "logo_bg_2_31001",
          "filename": "31001.png",
          "path": "/assets/backgrounds/logo_bg_2/31001.png"
        },
        {
          "id": "logo_bg_2_31002",
          "filename": "31002.png",
          "path": "/assets/backgrounds/logo_bg_2/31002.png"
        },
        {
          "id": "logo_bg_2_31003",
          "filename": "31003.png",
          "path": "/assets/backgrounds/logo_bg_2/31003.png"
        },
        {
          "id": "logo_bg_2_31004",
          "filename": "31004.png",
          "path": "/assets/backgrounds/logo_bg_2/31004.png"
        },
        {
          "id": "logo_bg_2_31005",
          "filename": "31005.png",
          "path": "/assets/backgrounds/logo_bg_2/31005.png"
        },
        {
          "id": "logo_bg_2_31006",
          "filename": "31006.png",
          "path": "/assets/backgrounds/logo_bg_2/31006.png"
        },
        {
          "id": "logo_bg_2_31007",
          "filename": "31007.png",
          "path": "/assets/backgrounds/logo_bg_2/31007.png"
        },
        {
          "id": "logo_bg_2_31008",
          "filename": "31008.png",
          "path": "/assets/backgrounds/logo_bg_2/31008.png"
        },
        {
          "id": "logo_bg_2_31009",
          "filename": "31009.png",
          "path": "/assets/backgrounds/logo_bg_2/31009.png"
        },
        {
          "id": "logo_bg_2_31010",
          "filename": "31010.png",
          "path": "/assets/backgrounds/logo_bg_2/31010.png"
        },
        {
          "id": "logo_bg_2_31011",
          "filename": "31011.png",
          "path": "/assets/backgrounds/logo_bg_2/31011.png"
        },
        {
          "id": "logo_bg_2_31012",
          "filename": "31012.png",
          "path": "/assets/backgrounds/logo_bg_2/31012.png"
        },
        {
          "id": "logo_bg_2_31013",
          "filename": "31013.png",
          "path": "/assets/backgrounds/logo_bg_2/31013.png"
        },
        {
          "id": "logo_bg_2_31014",
          "filename": "31014.png",
          "path": "/assets/backgrounds/logo_bg_2/31014.png"
        },
        {
          "id": "logo_bg_2_31015",
          "filename": "31015.png",
          "path": "/assets/backgrounds/logo_bg_2/31015.png"
        },
        {
          "id": "logo_bg_2_31016",
          "filename": "31016.png",
          "path": "/assets/backgrounds/logo_bg_2/31016.png"
        },
        {
          "id": "logo_bg_2_31017",
          "filename": "31017.png",
          "path": "/assets/backgrounds/logo_bg_2/31017.png"
        },
        {
          "id": "logo_bg_2_31018",
          "filename": "31018.png",
          "path": "/assets/backgrounds/logo_bg_2/31018.png"
        },
        {
          "id": "logo_bg_2_31019",
          "filename": "31019.png",
          "path": "/assets/backgrounds/logo_bg_2/31019.png"
        },
        {
          "id": "logo_bg_2_31020",
          "filename": "31020.png",
          "path": "/assets/backgrounds/logo_bg_2/31020.png"
        },
        {
          "id": "logo_bg_2_31021",
          "filename": "31021.png",
          "path": "/assets/backgrounds/logo_bg_2/31021.png"
        },
        {
          "id": "logo_bg_2_31022",
          "filename": "31022.png",
          "path": "/assets/backgrounds/logo_bg_2/31022.png"
        },
        {
          "id": "logo_bg_2_31023",
          "filename": "31023.png",
          "path": "/assets/backgrounds/logo_bg_2/31023.png"
        },
        {
          "id": "logo_bg_2_31024",
          "filename": "31024.png",
          "path": "/assets/backgrounds/logo_bg_2/31024.png"
        },
        {
          "id": "logo_bg_2_31025",
          "filename": "31025.png",
          "path": "/assets/backgrounds/logo_bg_2/31025.png"
        },
        {
          "id": "logo_bg_2_31026",
          "filename": "31026.png",
          "path": "/assets/backgrounds/logo_bg_2/31026.png"
        },
        {
          "id": "logo_bg_2_31027",
          "filename": "31027.png",
          "path": "/assets/backgrounds/logo_bg_2/31027.png"
        },
        {
          "id": "logo_bg_2_31028",
          "filename": "31028.png",
          "path": "/assets/backgrounds/logo_bg_2/31028.png"
        },
        {
          "id": "logo_bg_2_31029",
          "filename": "31029.png",
          "path": "/assets/backgrounds/logo_bg_2/31029.png"
        },
        {
          "id": "logo_bg_2_31030",
          "filename": "31030.png",
          "path": "/assets/backgrounds/logo_bg_2/31030.png"
        },
        {
          "id": "logo_bg_2_31031",
          "filename": "31031.png",
          "path": "/assets/backgrounds/logo_bg_2/31031.png"
        },
        {
          "id": "logo_bg_2_31032",
          "filename": "31032.png",
          "path": "/assets/backgrounds/logo_bg_2/31032.png"
        },
        {
          "id": "logo_bg_2_31033",
          "filename": "31033.png",
          "path": "/assets/backgrounds/logo_bg_2/31033.png"
        },
        {
          "id": "logo_bg_2_31034",
          "filename": "31034.png",
          "path": "/assets/backgrounds/logo_bg_2/31034.png"
        },
        {
          "id": "logo_bg_2_31035",
          "filename": "31035.png",
          "path": "/assets/backgrounds/logo_bg_2/31035.png"
        },
        {
          "id": "logo_bg_2_31036",
          "filename": "31036.png",
          "path": "/assets/backgrounds/logo_bg_2/31036.png"
        },
        {
          "id": "logo_bg_2_31037",
          "filename": "31037.png",
          "path": "/assets/backgrounds/logo_bg_2/31037.png"
        },
        {
          "id": "logo_bg_2_31038",
          "filename": "31038.png",
          "path": "/assets/backgrounds/logo_bg_2/31038.png"
        },
        {
          "id": "logo_bg_2_31039",
          "filename": "31039.png",
          "path": "/assets/backgrounds/logo_bg_2/31039.png"
        },
        {
          "id": "logo_bg_2_31040",
          "filename": "31040.png",
          "path": "/assets/backgrounds/logo_bg_2/31040.png"
        },
        {
          "id": "logo_bg_2_31041",
          "filename": "31041.png",
          "path": "/assets/backgrounds/logo_bg_2/31041.png"
        },
        {
          "id": "logo_bg_2_31042",
          "filename": "31042.png",
          "path": "/assets/backgrounds/logo_bg_2/31042.png"
        },
        {
          "id": "logo_bg_2_31043",
          "filename": "31043.png",
          "path": "/assets/backgrounds/logo_bg_2/31043.png"
        },
        {
          "id": "logo_bg_2_31044",
          "filename": "31044.png",
          "path": "/assets/backgrounds/logo_bg_2/31044.png"
        },
        {
          "id": "logo_bg_2_31045",
          "filename": "31045.png",
          "path": "/assets/backgrounds/logo_bg_2/31045.png"
        },
        {
          "id": "logo_bg_2_31046",
          "filename": "31046.png",
          "path": "/assets/backgrounds/logo_bg_2/31046.png"
        }
      ]
    },
    {
      "id": "logo_bg_3",
      "name": "Bg 3",
      "path": "/assets/backgrounds/logo_bg_3",
      "assets": [
        {
          "id": "logo_bg_3_32001",
          "filename": "32001.png",
          "path": "/assets/backgrounds/logo_bg_3/32001.png"
        },
        {
          "id": "logo_bg_3_32002",
          "filename": "32002.png",
          "path": "/assets/backgrounds/logo_bg_3/32002.png"
        },
        {
          "id": "logo_bg_3_32003",
          "filename": "32003.png",
          "path": "/assets/backgrounds/logo_bg_3/32003.png"
        },
        {
          "id": "logo_bg_3_32004",
          "filename": "32004.png",
          "path": "/assets/backgrounds/logo_bg_3/32004.png"
        },
        {
          "id": "logo_bg_3_32005",
          "filename": "32005.png",
          "path": "/assets/backgrounds/logo_bg_3/32005.png"
        },
        {
          "id": "logo_bg_3_32006",
          "filename": "32006.png",
          "path": "/assets/backgrounds/logo_bg_3/32006.png"
        },
        {
          "id": "logo_bg_3_32007",
          "filename": "32007.png",
          "path": "/assets/backgrounds/logo_bg_3/32007.png"
        },
        {
          "id": "logo_bg_3_32008",
          "filename": "32008.png",
          "path": "/assets/backgrounds/logo_bg_3/32008.png"
        },
        {
          "id": "logo_bg_3_32009",
          "filename": "32009.png",
          "path": "/assets/backgrounds/logo_bg_3/32009.png"
        },
        {
          "id": "logo_bg_3_32010",
          "filename": "32010.png",
          "path": "/assets/backgrounds/logo_bg_3/32010.png"
        },
        {
          "id": "logo_bg_3_32011",
          "filename": "32011.png",
          "path": "/assets/backgrounds/logo_bg_3/32011.png"
        },
        {
          "id": "logo_bg_3_32012",
          "filename": "32012.png",
          "path": "/assets/backgrounds/logo_bg_3/32012.png"
        },
        {
          "id": "logo_bg_3_32013",
          "filename": "32013.png",
          "path": "/assets/backgrounds/logo_bg_3/32013.png"
        },
        {
          "id": "logo_bg_3_32014",
          "filename": "32014.png",
          "path": "/assets/backgrounds/logo_bg_3/32014.png"
        },
        {
          "id": "logo_bg_3_32015",
          "filename": "32015.png",
          "path": "/assets/backgrounds/logo_bg_3/32015.png"
        },
        {
          "id": "logo_bg_3_32016",
          "filename": "32016.png",
          "path": "/assets/backgrounds/logo_bg_3/32016.png"
        },
        {
          "id": "logo_bg_3_32017",
          "filename": "32017.png",
          "path": "/assets/backgrounds/logo_bg_3/32017.png"
        },
        {
          "id": "logo_bg_3_32018",
          "filename": "32018.png",
          "path": "/assets/backgrounds/logo_bg_3/32018.png"
        },
        {
          "id": "logo_bg_3_32019",
          "filename": "32019.png",
          "path": "/assets/backgrounds/logo_bg_3/32019.png"
        },
        {
          "id": "logo_bg_3_32020",
          "filename": "32020.png",
          "path": "/assets/backgrounds/logo_bg_3/32020.png"
        },
        {
          "id": "logo_bg_3_32021",
          "filename": "32021.png",
          "path": "/assets/backgrounds/logo_bg_3/32021.png"
        },
        {
          "id": "logo_bg_3_32022",
          "filename": "32022.png",
          "path": "/assets/backgrounds/logo_bg_3/32022.png"
        },
        {
          "id": "logo_bg_3_32023",
          "filename": "32023.png",
          "path": "/assets/backgrounds/logo_bg_3/32023.png"
        },
        {
          "id": "logo_bg_3_32024",
          "filename": "32024.png",
          "path": "/assets/backgrounds/logo_bg_3/32024.png"
        },
        {
          "id": "logo_bg_3_32025",
          "filename": "32025.png",
          "path": "/assets/backgrounds/logo_bg_3/32025.png"
        },
        {
          "id": "logo_bg_3_32026",
          "filename": "32026.png",
          "path": "/assets/backgrounds/logo_bg_3/32026.png"
        },
        {
          "id": "logo_bg_3_32027",
          "filename": "32027.png",
          "path": "/assets/backgrounds/logo_bg_3/32027.png"
        }
      ]
    },
    {
      "id": "logo_bg_4",
      "name": "Bg 4",
      "path": "/assets/backgrounds/logo_bg_4",
      "assets": [
        {
          "id": "logo_bg_4_33001",
          "filename": "33001.png",
          "path": "/assets/backgrounds/logo_bg_4/33001.png"
        },
        {
          "id": "logo_bg_4_33002",
          "filename": "33002.png",
          "path": "/assets/backgrounds/logo_bg_4/33002.png"
        },
        {
          "id": "logo_bg_4_33003",
          "filename": "33003.png",
          "path": "/assets/backgrounds/logo_bg_4/33003.png"
        },
        {
          "id": "logo_bg_4_33004",
          "filename": "33004.png",
          "path": "/assets/backgrounds/logo_bg_4/33004.png"
        },
        {
          "id": "logo_bg_4_33005",
          "filename": "33005.png",
          "path": "/assets/backgrounds/logo_bg_4/33005.png"
        },
        {
          "id": "logo_bg_4_33006",
          "filename": "33006.png",
          "path": "/assets/backgrounds/logo_bg_4/33006.png"
        },
        {
          "id": "logo_bg_4_33007",
          "filename": "33007.png",
          "path": "/assets/backgrounds/logo_bg_4/33007.png"
        },
        {
          "id": "logo_bg_4_33008",
          "filename": "33008.png",
          "path": "/assets/backgrounds/logo_bg_4/33008.png"
        }
      ]
    },
    {
      "id": "logo_bg_5",
      "name": "Bg 5",
      "path": "/assets/backgrounds/logo_bg_5",
      "assets": [
        {
          "id": "logo_bg_5_34001",
          "filename": "34001.png",
          "path": "/assets/backgrounds/logo_bg_5/34001.png"
        },
        {
          "id": "logo_bg_5_34002",
          "filename": "34002.png",
          "path": "/assets/backgrounds/logo_bg_5/34002.png"
        },
        {
          "id": "logo_bg_5_34003",
          "filename": "34003.png",
          "path": "/assets/backgrounds/logo_bg_5/34003.png"
        },
        {
          "id": "logo_bg_5_34004",
          "filename": "34004.png",
          "path": "/assets/backgrounds/logo_bg_5/34004.png"
        },
        {
          "id": "logo_bg_5_34005",
          "filename": "34005.png",
          "path": "/assets/backgrounds/logo_bg_5/34005.png"
        },
        {
          "id": "logo_bg_5_34006",
          "filename": "34006.png",
          "path": "/assets/backgrounds/logo_bg_5/34006.png"
        },
        {
          "id": "logo_bg_5_34007",
          "filename": "34007.png",
          "path": "/assets/backgrounds/logo_bg_5/34007.png"
        },
        {
          "id": "logo_bg_5_34008",
          "filename": "34008.png",
          "path": "/assets/backgrounds/logo_bg_5/34008.png"
        },
        {
          "id": "logo_bg_5_34009",
          "filename": "34009.png",
          "path": "/assets/backgrounds/logo_bg_5/34009.png"
        },
        {
          "id": "logo_bg_5_34010",
          "filename": "34010.png",
          "path": "/assets/backgrounds/logo_bg_5/34010.png"
        },
        {
          "id": "logo_bg_5_34011",
          "filename": "34011.png",
          "path": "/assets/backgrounds/logo_bg_5/34011.png"
        },
        {
          "id": "logo_bg_5_34012",
          "filename": "34012.png",
          "path": "/assets/backgrounds/logo_bg_5/34012.png"
        },
        {
          "id": "logo_bg_5_34013",
          "filename": "34013.png",
          "path": "/assets/backgrounds/logo_bg_5/34013.png"
        },
        {
          "id": "logo_bg_5_34014",
          "filename": "34014.png",
          "path": "/assets/backgrounds/logo_bg_5/34014.png"
        },
        {
          "id": "logo_bg_5_34015",
          "filename": "34015.png",
          "path": "/assets/backgrounds/logo_bg_5/34015.png"
        },
        {
          "id": "logo_bg_5_34016",
          "filename": "34016.png",
          "path": "/assets/backgrounds/logo_bg_5/34016.png"
        },
        {
          "id": "logo_bg_5_34017",
          "filename": "34017.png",
          "path": "/assets/backgrounds/logo_bg_5/34017.png"
        },
        {
          "id": "logo_bg_5_34018",
          "filename": "34018.png",
          "path": "/assets/backgrounds/logo_bg_5/34018.png"
        },
        {
          "id": "logo_bg_5_34019",
          "filename": "34019.png",
          "path": "/assets/backgrounds/logo_bg_5/34019.png"
        },
        {
          "id": "logo_bg_5_34020",
          "filename": "34020.png",
          "path": "/assets/backgrounds/logo_bg_5/34020.png"
        },
        {
          "id": "logo_bg_5_34021",
          "filename": "34021.png",
          "path": "/assets/backgrounds/logo_bg_5/34021.png"
        },
        {
          "id": "logo_bg_5_34022",
          "filename": "34022.png",
          "path": "/assets/backgrounds/logo_bg_5/34022.png"
        },
        {
          "id": "logo_bg_5_34023",
          "filename": "34023.png",
          "path": "/assets/backgrounds/logo_bg_5/34023.png"
        },
        {
          "id": "logo_bg_5_34024",
          "filename": "34024.png",
          "path": "/assets/backgrounds/logo_bg_5/34024.png"
        },
        {
          "id": "logo_bg_5_34025",
          "filename": "34025.png",
          "path": "/assets/backgrounds/logo_bg_5/34025.png"
        },
        {
          "id": "logo_bg_5_34026",
          "filename": "34026.png",
          "path": "/assets/backgrounds/logo_bg_5/34026.png"
        },
        {
          "id": "logo_bg_5_34027",
          "filename": "34027.png",
          "path": "/assets/backgrounds/logo_bg_5/34027.png"
        },
        {
          "id": "logo_bg_5_34028",
          "filename": "34028.png",
          "path": "/assets/backgrounds/logo_bg_5/34028.png"
        },
        {
          "id": "logo_bg_5_34029",
          "filename": "34029.png",
          "path": "/assets/backgrounds/logo_bg_5/34029.png"
        },
        {
          "id": "logo_bg_5_34030",
          "filename": "34030.png",
          "path": "/assets/backgrounds/logo_bg_5/34030.png"
        },
        {
          "id": "logo_bg_5_34031",
          "filename": "34031.png",
          "path": "/assets/backgrounds/logo_bg_5/34031.png"
        },
        {
          "id": "logo_bg_5_34032",
          "filename": "34032.png",
          "path": "/assets/backgrounds/logo_bg_5/34032.png"
        },
        {
          "id": "logo_bg_5_34033",
          "filename": "34033.png",
          "path": "/assets/backgrounds/logo_bg_5/34033.png"
        },
        {
          "id": "logo_bg_5_34034",
          "filename": "34034.png",
          "path": "/assets/backgrounds/logo_bg_5/34034.png"
        },
        {
          "id": "logo_bg_5_34035",
          "filename": "34035.png",
          "path": "/assets/backgrounds/logo_bg_5/34035.png"
        },
        {
          "id": "logo_bg_5_34036",
          "filename": "34036.png",
          "path": "/assets/backgrounds/logo_bg_5/34036.png"
        },
        {
          "id": "logo_bg_5_34037",
          "filename": "34037.png",
          "path": "/assets/backgrounds/logo_bg_5/34037.png"
        },
        {
          "id": "logo_bg_5_34038",
          "filename": "34038.png",
          "path": "/assets/backgrounds/logo_bg_5/34038.png"
        },
        {
          "id": "logo_bg_5_34039",
          "filename": "34039.png",
          "path": "/assets/backgrounds/logo_bg_5/34039.png"
        },
        {
          "id": "logo_bg_5_34040",
          "filename": "34040.png",
          "path": "/assets/backgrounds/logo_bg_5/34040.png"
        },
        {
          "id": "logo_bg_5_34041",
          "filename": "34041.png",
          "path": "/assets/backgrounds/logo_bg_5/34041.png"
        },
        {
          "id": "logo_bg_5_34042",
          "filename": "34042.png",
          "path": "/assets/backgrounds/logo_bg_5/34042.png"
        },
        {
          "id": "logo_bg_5_34043",
          "filename": "34043.png",
          "path": "/assets/backgrounds/logo_bg_5/34043.png"
        },
        {
          "id": "logo_bg_5_34044",
          "filename": "34044.png",
          "path": "/assets/backgrounds/logo_bg_5/34044.png"
        },
        {
          "id": "logo_bg_5_34045",
          "filename": "34045.png",
          "path": "/assets/backgrounds/logo_bg_5/34045.png"
        },
        {
          "id": "logo_bg_5_34046",
          "filename": "34046.png",
          "path": "/assets/backgrounds/logo_bg_5/34046.png"
        }
      ]
    }
  ],
  "middle": [
    {
      "id": "logo_middle_1",
      "name": "Middle 1",
      "path": "/assets/middle/logo_middle_1",
      "assets": [
        {
          "id": "logo_middle_1_B001",
          "filename": "B001.png",
          "path": "/assets/middle/logo_middle_1/B001.png"
        },
        {
          "id": "logo_middle_1_B002",
          "filename": "B002.png",
          "path": "/assets/middle/logo_middle_1/B002.png"
        },
        {
          "id": "logo_middle_1_B003",
          "filename": "B003.png",
          "path": "/assets/middle/logo_middle_1/B003.png"
        },
        {
          "id": "logo_middle_1_B004",
          "filename": "B004.png",
          "path": "/assets/middle/logo_middle_1/B004.png"
        },
        {
          "id": "logo_middle_1_B005",
          "filename": "B005.png",
          "path": "/assets/middle/logo_middle_1/B005.png"
        },
        {
          "id": "logo_middle_1_B006",
          "filename": "B006.png",
          "path": "/assets/middle/logo_middle_1/B006.png"
        },
        {
          "id": "logo_middle_1_B007",
          "filename": "B007.png",
          "path": "/assets/middle/logo_middle_1/B007.png"
        },
        {
          "id": "logo_middle_1_B008",
          "filename": "B008.png",
          "path": "/assets/middle/logo_middle_1/B008.png"
        },
        {
          "id": "logo_middle_1_B009",
          "filename": "B009.png",
          "path": "/assets/middle/logo_middle_1/B009.png"
        },
        {
          "id": "logo_middle_1_B010",
          "filename": "B010.png",
          "path": "/assets/middle/logo_middle_1/B010.png"
        },
        {
          "id": "logo_middle_1_B011",
          "filename": "B011.png",
          "path": "/assets/middle/logo_middle_1/B011.png"
        },
        {
          "id": "logo_middle_1_B012",
          "filename": "B012.png",
          "path": "/assets/middle/logo_middle_1/B012.png"
        },
        {
          "id": "logo_middle_1_B013",
          "filename": "B013.png",
          "path": "/assets/middle/logo_middle_1/B013.png"
        },
        {
          "id": "logo_middle_1_B014",
          "filename": "B014.png",
          "path": "/assets/middle/logo_middle_1/B014.png"
        },
        {
          "id": "logo_middle_1_B015",
          "filename": "B015.png",
          "path": "/assets/middle/logo_middle_1/B015.png"
        },
        {
          "id": "logo_middle_1_B016",
          "filename": "B016.png",
          "path": "/assets/middle/logo_middle_1/B016.png"
        },
        {
          "id": "logo_middle_1_B017",
          "filename": "B017.png",
          "path": "/assets/middle/logo_middle_1/B017.png"
        },
        {
          "id": "logo_middle_1_B018",
          "filename": "B018.png",
          "path": "/assets/middle/logo_middle_1/B018.png"
        },
        {
          "id": "logo_middle_1_B019",
          "filename": "B019.png",
          "path": "/assets/middle/logo_middle_1/B019.png"
        },
        {
          "id": "logo_middle_1_B020",
          "filename": "B020.png",
          "path": "/assets/middle/logo_middle_1/B020.png"
        },
        {
          "id": "logo_middle_1_B021",
          "filename": "B021.png",
          "path": "/assets/middle/logo_middle_1/B021.png"
        },
        {
          "id": "logo_middle_1_B022",
          "filename": "B022.png",
          "path": "/assets/middle/logo_middle_1/B022.png"
        },
        {
          "id": "logo_middle_1_B023",
          "filename": "B023.png",
          "path": "/assets/middle/logo_middle_1/B023.png"
        },
        {
          "id": "logo_middle_1_B024",
          "filename": "B024.png",
          "path": "/assets/middle/logo_middle_1/B024.png"
        },
        {
          "id": "logo_middle_1_B025",
          "filename": "B025.png",
          "path": "/assets/middle/logo_middle_1/B025.png"
        },
        {
          "id": "logo_middle_1_B026",
          "filename": "B026.png",
          "path": "/assets/middle/logo_middle_1/B026.png"
        }
      ]
    },
    {
      "id": "logo_middle_2",
      "name": "Middle 2",
      "path": "/assets/middle/logo_middle_2",
      "assets": [
        {
          "id": "logo_middle_2_B101",
          "filename": "B101.png",
          "path": "/assets/middle/logo_middle_2/B101.png"
        },
        {
          "id": "logo_middle_2_B102",
          "filename": "B102.png",
          "path": "/assets/middle/logo_middle_2/B102.png"
        },
        {
          "id": "logo_middle_2_B103",
          "filename": "B103.png",
          "path": "/assets/middle/logo_middle_2/B103.png"
        },
        {
          "id": "logo_middle_2_B104",
          "filename": "B104.png",
          "path": "/assets/middle/logo_middle_2/B104.png"
        },
        {
          "id": "logo_middle_2_B105",
          "filename": "B105.png",
          "path": "/assets/middle/logo_middle_2/B105.png"
        },
        {
          "id": "logo_middle_2_B106",
          "filename": "B106.png",
          "path": "/assets/middle/logo_middle_2/B106.png"
        },
        {
          "id": "logo_middle_2_B107",
          "filename": "B107.png",
          "path": "/assets/middle/logo_middle_2/B107.png"
        },
        {
          "id": "logo_middle_2_B108",
          "filename": "B108.png",
          "path": "/assets/middle/logo_middle_2/B108.png"
        },
        {
          "id": "logo_middle_2_B109",
          "filename": "B109.png",
          "path": "/assets/middle/logo_middle_2/B109.png"
        },
        {
          "id": "logo_middle_2_B110",
          "filename": "B110.png",
          "path": "/assets/middle/logo_middle_2/B110.png"
        },
        {
          "id": "logo_middle_2_B111",
          "filename": "B111.png",
          "path": "/assets/middle/logo_middle_2/B111.png"
        },
        {
          "id": "logo_middle_2_B112",
          "filename": "B112.png",
          "path": "/assets/middle/logo_middle_2/B112.png"
        },
        {
          "id": "logo_middle_2_B113",
          "filename": "B113.png",
          "path": "/assets/middle/logo_middle_2/B113.png"
        },
        {
          "id": "logo_middle_2_B114",
          "filename": "B114.png",
          "path": "/assets/middle/logo_middle_2/B114.png"
        },
        {
          "id": "logo_middle_2_B115",
          "filename": "B115.png",
          "path": "/assets/middle/logo_middle_2/B115.png"
        },
        {
          "id": "logo_middle_2_B116",
          "filename": "B116.png",
          "path": "/assets/middle/logo_middle_2/B116.png"
        },
        {
          "id": "logo_middle_2_B117",
          "filename": "B117.png",
          "path": "/assets/middle/logo_middle_2/B117.png"
        },
        {
          "id": "logo_middle_2_B118",
          "filename": "B118.png",
          "path": "/assets/middle/logo_middle_2/B118.png"
        },
        {
          "id": "logo_middle_2_B119",
          "filename": "B119.png",
          "path": "/assets/middle/logo_middle_2/B119.png"
        },
        {
          "id": "logo_middle_2_B120",
          "filename": "B120.png",
          "path": "/assets/middle/logo_middle_2/B120.png"
        },
        {
          "id": "logo_middle_2_B121",
          "filename": "B121.png",
          "path": "/assets/middle/logo_middle_2/B121.png"
        },
        {
          "id": "logo_middle_2_B122",
          "filename": "B122.png",
          "path": "/assets/middle/logo_middle_2/B122.png"
        }
      ]
    }
  ],
  "foreground": [
    {
      "id": "logo_foreground",
      "name": "Foreground",
      "path": "/assets/foreground/logo_foreground",
      "assets": [
        {
          "id": "logo_foreground_D001",
          "filename": "D001.png",
          "path": "/assets/foreground/logo_foreground/D001.png"
        },
        {
          "id": "logo_foreground_D002",
          "filename": "D002.png",
          "path": "/assets/foreground/logo_foreground/D002.png"
        },
        {
          "id": "logo_foreground_D003",
          "filename": "D003.png",
          "path": "/assets/foreground/logo_foreground/D003.png"
        },
        {
          "id": "logo_foreground_D004",
          "filename": "D004.png",
          "path": "/assets/foreground/logo_foreground/D004.png"
        },
        {
          "id": "logo_foreground_D005",
          "filename": "D005.png",
          "path": "/assets/foreground/logo_foreground/D005.png"
        },
        {
          "id": "logo_foreground_D006",
          "filename": "D006.png",
          "path": "/assets/foreground/logo_foreground/D006.png"
        },
        {
          "id": "logo_foreground_D007",
          "filename": "D007.png",
          "path": "/assets/foreground/logo_foreground/D007.png"
        },
        {
          "id": "logo_foreground_D008",
          "filename": "D008.png",
          "path": "/assets/foreground/logo_foreground/D008.png"
        },
        {
          "id": "logo_foreground_D009",
          "filename": "D009.png",
          "path": "/assets/foreground/logo_foreground/D009.png"
        },
        {
          "id": "logo_foreground_D010",
          "filename": "D010.png",
          "path": "/assets/foreground/logo_foreground/D010.png"
        },
        {
          "id": "logo_foreground_D011",
          "filename": "D011.png",
          "path": "/assets/foreground/logo_foreground/D011.png"
        },
        {
          "id": "logo_foreground_D012",
          "filename": "D012.png",
          "path": "/assets/foreground/logo_foreground/D012.png"
        },
        {
          "id": "logo_foreground_D013",
          "filename": "D013.png",
          "path": "/assets/foreground/logo_foreground/D013.png"
        },
        {
          "id": "logo_foreground_D014",
          "filename": "D014.png",
          "path": "/assets/foreground/logo_foreground/D014.png"
        },
        {
          "id": "logo_foreground_D015",
          "filename": "D015.png",
          "path": "/assets/foreground/logo_foreground/D015.png"
        },
        {
          "id": "logo_foreground_D016",
          "filename": "D016.png",
          "path": "/assets/foreground/logo_foreground/D016.png"
        },
        {
          "id": "logo_foreground_D017",
          "filename": "D017.png",
          "path": "/assets/foreground/logo_foreground/D017.png"
        },
        {
          "id": "logo_foreground_D018",
          "filename": "D018.png",
          "path": "/assets/foreground/logo_foreground/D018.png"
        },
        {
          "id": "logo_foreground_D019",
          "filename": "D019.png",
          "path": "/assets/foreground/logo_foreground/D019.png"
        },
        {
          "id": "logo_foreground_D020",
          "filename": "D020.png",
          "path": "/assets/foreground/logo_foreground/D020.png"
        },
        {
          "id": "logo_foreground_D021",
          "filename": "D021.png",
          "path": "/assets/foreground/logo_foreground/D021.png"
        },
        {
          "id": "logo_foreground_D022",
          "filename": "D022.png",
          "path": "/assets/foreground/logo_foreground/D022.png"
        },
        {
          "id": "logo_foreground_D023",
          "filename": "D023.png",
          "path": "/assets/foreground/logo_foreground/D023.png"
        },
        {
          "id": "logo_foreground_D024",
          "filename": "D024.png",
          "path": "/assets/foreground/logo_foreground/D024.png"
        },
        {
          "id": "logo_foreground_D025",
          "filename": "D025.png",
          "path": "/assets/foreground/logo_foreground/D025.png"
        },
        {
          "id": "logo_foreground_D026",
          "filename": "D026.png",
          "path": "/assets/foreground/logo_foreground/D026.png"
        },
        {
          "id": "logo_foreground_D027",
          "filename": "D027.png",
          "path": "/assets/foreground/logo_foreground/D027.png"
        },
        {
          "id": "logo_foreground_D028",
          "filename": "D028.png",
          "path": "/assets/foreground/logo_foreground/D028.png"
        },
        {
          "id": "logo_foreground_D029",
          "filename": "D029.png",
          "path": "/assets/foreground/logo_foreground/D029.png"
        },
        {
          "id": "logo_foreground_D030",
          "filename": "D030.png",
          "path": "/assets/foreground/logo_foreground/D030.png"
        },
        {
          "id": "logo_foreground_D031",
          "filename": "D031.png",
          "path": "/assets/foreground/logo_foreground/D031.png"
        },
        {
          "id": "logo_foreground_D032",
          "filename": "D032.png",
          "path": "/assets/foreground/logo_foreground/D032.png"
        },
        {
          "id": "logo_foreground_D033",
          "filename": "D033.png",
          "path": "/assets/foreground/logo_foreground/D033.png"
        },
        {
          "id": "logo_foreground_D034",
          "filename": "D034.png",
          "path": "/assets/foreground/logo_foreground/D034.png"
        },
        {
          "id": "logo_foreground_D035",
          "filename": "D035.png",
          "path": "/assets/foreground/logo_foreground/D035.png"
        },
        {
          "id": "logo_foreground_D036",
          "filename": "D036.png",
          "path": "/assets/foreground/logo_foreground/D036.png"
        },
        {
          "id": "logo_foreground_D037",
          "filename": "D037.png",
          "path": "/assets/foreground/logo_foreground/D037.png"
        },
        {
          "id": "logo_foreground_D038",
          "filename": "D038.png",
          "path": "/assets/foreground/logo_foreground/D038.png"
        },
        {
          "id": "logo_foreground_D039",
          "filename": "D039.png",
          "path": "/assets/foreground/logo_foreground/D039.png"
        },
        {
          "id": "logo_foreground_D040",
          "filename": "D040.png",
          "path": "/assets/foreground/logo_foreground/D040.png"
        },
        {
          "id": "logo_foreground_D041",
          "filename": "D041.png",
          "path": "/assets/foreground/logo_foreground/D041.png"
        },
        {
          "id": "logo_foreground_D042",
          "filename": "D042.png",
          "path": "/assets/foreground/logo_foreground/D042.png"
        },
        {
          "id": "logo_foreground_D043",
          "filename": "D043.png",
          "path": "/assets/foreground/logo_foreground/D043.png"
        },
        {
          "id": "logo_foreground_D044",
          "filename": "D044.png",
          "path": "/assets/foreground/logo_foreground/D044.png"
        },
        {
          "id": "logo_foreground_D045",
          "filename": "D045.png",
          "path": "/assets/foreground/logo_foreground/D045.png"
        },
        {
          "id": "logo_foreground_D046",
          "filename": "D046.png",
          "path": "/assets/foreground/logo_foreground/D046.png"
        },
        {
          "id": "logo_foreground_D047",
          "filename": "D047.png",
          "path": "/assets/foreground/logo_foreground/D047.png"
        },
        {
          "id": "logo_foreground_D048",
          "filename": "D048.png",
          "path": "/assets/foreground/logo_foreground/D048.png"
        },
        {
          "id": "logo_foreground_D049",
          "filename": "D049.png",
          "path": "/assets/foreground/logo_foreground/D049.png"
        },
        {
          "id": "logo_foreground_D050",
          "filename": "D050.png",
          "path": "/assets/foreground/logo_foreground/D050.png"
        },
        {
          "id": "logo_foreground_D051",
          "filename": "D051.png",
          "path": "/assets/foreground/logo_foreground/D051.png"
        },
        {
          "id": "logo_foreground_D052",
          "filename": "D052.png",
          "path": "/assets/foreground/logo_foreground/D052.png"
        },
        {
          "id": "logo_foreground_D053",
          "filename": "D053.png",
          "path": "/assets/foreground/logo_foreground/D053.png"
        },
        {
          "id": "logo_foreground_D054",
          "filename": "D054.png",
          "path": "/assets/foreground/logo_foreground/D054.png"
        },
        {
          "id": "logo_foreground_D055",
          "filename": "D055.png",
          "path": "/assets/foreground/logo_foreground/D055.png"
        },
        {
          "id": "logo_foreground_D056",
          "filename": "D056.png",
          "path": "/assets/foreground/logo_foreground/D056.png"
        },
        {
          "id": "logo_foreground_D057",
          "filename": "D057.png",
          "path": "/assets/foreground/logo_foreground/D057.png"
        },
        {
          "id": "logo_foreground_D058",
          "filename": "D058.png",
          "path": "/assets/foreground/logo_foreground/D058.png"
        },
        {
          "id": "logo_foreground_D059",
          "filename": "D059.png",
          "path": "/assets/foreground/logo_foreground/D059.png"
        },
        {
          "id": "logo_foreground_D060",
          "filename": "D060.png",
          "path": "/assets/foreground/logo_foreground/D060.png"
        },
        {
          "id": "logo_foreground_D061",
          "filename": "D061.png",
          "path": "/assets/foreground/logo_foreground/D061.png"
        },
        {
          "id": "logo_foreground_D062",
          "filename": "D062.png",
          "path": "/assets/foreground/logo_foreground/D062.png"
        },
        {
          "id": "logo_foreground_D063",
          "filename": "D063.png",
          "path": "/assets/foreground/logo_foreground/D063.png"
        },
        {
          "id": "logo_foreground_D064",
          "filename": "D064.png",
          "path": "/assets/foreground/logo_foreground/D064.png"
        },
        {
          "id": "logo_foreground_D065",
          "filename": "D065.png",
          "path": "/assets/foreground/logo_foreground/D065.png"
        },
        {
          "id": "logo_foreground_D066",
          "filename": "D066.png",
          "path": "/assets/foreground/logo_foreground/D066.png"
        },
        {
          "id": "logo_foreground_D067",
          "filename": "D067.png",
          "path": "/assets/foreground/logo_foreground/D067.png"
        },
        {
          "id": "logo_foreground_D068",
          "filename": "D068.png",
          "path": "/assets/foreground/logo_foreground/D068.png"
        },
        {
          "id": "logo_foreground_D069",
          "filename": "D069.png",
          "path": "/assets/foreground/logo_foreground/D069.png"
        },
        {
          "id": "logo_foreground_D070",
          "filename": "D070.png",
          "path": "/assets/foreground/logo_foreground/D070.png"
        }
      ]
    }
  ]
} as const
